/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    DefaultHeader: typeof import('./src/components/layout/DefaultHeader.vue')['default']
    DefaultMenu: typeof import('./src/components/layout/DefaultMenu.vue')['default']
    PageLoading: typeof import('./src/components/UI/PageLoading.vue')['default']
    ProcessIndicator: typeof import('./src/components/UI/ProcessIndicator.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
