/**
 * OpenApi specification - My Spring App
 * OpenApi document for Spring Security
 *
 * OpenAPI spec version: 1.0
 * Contact: viet.hung.2898@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SortObject } from '../models/SortObject';
import { HttpFile } from '../http/http';

export class PageableObject {
    'offset'?: number;
    'sort'?: Array<SortObject>;
    'unpaged'?: boolean;
    'paged'?: boolean;
    'pageSize'?: number;
    'pageNumber'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "offset",
            "baseName": "offset",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "sort",
            "baseName": "sort",
            "type": "Array<SortObject>",
            "format": ""
        },
        {
            "name": "unpaged",
            "baseName": "unpaged",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "paged",
            "baseName": "paged",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "pageSize",
            "baseName": "pageSize",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "pageNumber",
            "baseName": "pageNumber",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return PageableObject.attributeTypeMap;
    }

    public constructor() {
    }
}
