/**
 * OpenApi specification - My Spring App
 * OpenApi document for Spring Security
 *
 * OpenAPI spec version: 1.0
 * Contact: viet.hung.2898@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class PermissionDto {
    'id': number;
    'name': PermissionDtoNameEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "PermissionDtoNameEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PermissionDto.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum PermissionDtoNameEnum {
    UserView = 'USER_VIEW',
    UserCreate = 'USER_CREATE',
    UserUpdate = 'USER_UPDATE',
    UserDelete = 'USER_DELETE',
    TimesheetView = 'TIMESHEET_VIEW',
    TimesheetCreate = 'TIMESHEET_CREATE',
    TimesheetApproval = 'TIMESHEET_APPROVAL'
}

