/**
 * OpenApi specification - My Spring App
 * OpenApi document for Spring Security
 *
 * OpenAPI spec version: 1.0
 * Contact: viet.hung.2898@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PermissionDto } from '../models/PermissionDto';
import { HttpFile } from '../http/http';

export class RoleCreateUpdateRequest {
    'name': string;
    'description'?: string;
    'admin'?: boolean;
    'level'?: number;
    'permissions'?: Array<PermissionDto>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "admin",
            "baseName": "admin",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "level",
            "baseName": "level",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "permissions",
            "baseName": "permissions",
            "type": "Array<PermissionDto>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RoleCreateUpdateRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
