/**
 * OpenApi specification - My Spring App
 * OpenApi document for Spring Security
 *
 * OpenAPI spec version: 1.0
 * Contact: viet.hung.2898@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SortObject {
    'direction'?: string;
    'nullHandling'?: string;
    'ascending'?: boolean;
    'property'?: string;
    'ignoreCase'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "direction",
            "baseName": "direction",
            "type": "string",
            "format": ""
        },
        {
            "name": "nullHandling",
            "baseName": "nullHandling",
            "type": "string",
            "format": ""
        },
        {
            "name": "ascending",
            "baseName": "ascending",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "property",
            "baseName": "property",
            "type": "string",
            "format": ""
        },
        {
            "name": "ignoreCase",
            "baseName": "ignoreCase",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SortObject.attributeTypeMap;
    }

    public constructor() {
    }
}
