/**
 * OpenApi specification - My Spring App
 * OpenApi document for Spring Security
 *
 * OpenAPI spec version: 1.0
 * Contact: viet.hung.2898@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class TicketRequest {
    'approverId': number;
    'type': TicketRequestTypeEnum;
    'description': string;
    'date': string;
    'typeSpecificData'?: { [key: string]: any; };

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "approverId",
            "baseName": "approverId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "TicketRequestTypeEnum",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "date",
            "baseName": "date",
            "type": "string",
            "format": "date"
        },
        {
            "name": "typeSpecificData",
            "baseName": "typeSpecificData",
            "type": "{ [key: string]: any; }",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TicketRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum TicketRequestTypeEnum {
    TimesheetAdjustment = 'TIMESHEET_ADJUSTMENT',
    LeaveRequest = 'LEAVE_REQUEST',
    OvertimeRequest = 'OVERTIME_REQUEST',
    WorkFromHome = 'WORK_FROM_HOME'
}

