/**
 * OpenApi specification - My Spring App
 * OpenApi document for Spring Security
 *
 * OpenAPI spec version: 1.0
 * Contact: viet.hung.2898@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Role } from './Role'
import { HttpFile } from '../http/http'

export class UserDto {
  'id'?: number
  'name'?: string
  'username'?: string
  'email'?: string
  'roles'?: Set<Role>

  static readonly discriminator: string | undefined = undefined

  static readonly mapping: { [index: string]: string } | undefined = undefined

  static readonly attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
    format: string
  }> = [
    {
      name: 'id',
      baseName: 'id',
      type: 'number',
      format: 'int64',
    },
    {
      name: 'name',
      baseName: 'name',
      type: 'string',
      format: '',
    },
    {
      name: 'username',
      baseName: 'username',
      type: 'string',
      format: '',
    },
    {
      name: 'email',
      baseName: 'email',
      type: 'string',
      format: '',
    },
    {
      name: 'roles',
      baseName: 'roles',
      type: 'Set<Role>',
      format: '',
    },
  ]

  static getAttributeTypeMap() {
    return UserDto.attributeTypeMap
  }

  public constructor() {}
}
