/**
 * OpenApi specification - My Spring App
 * OpenApi document for Spring Security
 *
 * OpenAPI spec version: 1.0
 * Contact: viet.hung.2898@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GrantedAuthority } from '../models/GrantedAuthority';
import { Role } from '../models/Role';
import { Team } from '../models/Team';
import { WorkTime } from '../models/WorkTime';
import { HttpFile } from '../http/http';

export class User {
    'id'?: number;
    'name'?: string;
    'username'?: string;
    'email'?: string;
    'position'?: UserPositionEnum;
    'supervisor'?: User;
    'roles'?: Set<Role>;
    'workTime'?: WorkTime;
    'team'?: Team;
    'status': UserStatusEnum;
    'enabled'?: boolean;
    'authorities'?: Array<GrantedAuthority>;
    'currentLevel'?: number;
    'accountNonExpired'?: boolean;
    'credentialsNonExpired'?: boolean;
    'accountNonLocked'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "username",
            "baseName": "username",
            "type": "string",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "position",
            "baseName": "position",
            "type": "UserPositionEnum",
            "format": ""
        },
        {
            "name": "supervisor",
            "baseName": "supervisor",
            "type": "User",
            "format": ""
        },
        {
            "name": "roles",
            "baseName": "roles",
            "type": "Set<Role>",
            "format": ""
        },
        {
            "name": "workTime",
            "baseName": "workTime",
            "type": "WorkTime",
            "format": ""
        },
        {
            "name": "team",
            "baseName": "team",
            "type": "Team",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "UserStatusEnum",
            "format": ""
        },
        {
            "name": "enabled",
            "baseName": "enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "authorities",
            "baseName": "authorities",
            "type": "Array<GrantedAuthority>",
            "format": ""
        },
        {
            "name": "currentLevel",
            "baseName": "currentLevel",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "accountNonExpired",
            "baseName": "accountNonExpired",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "credentialsNonExpired",
            "baseName": "credentialsNonExpired",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "accountNonLocked",
            "baseName": "accountNonLocked",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return User.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum UserPositionEnum {
    Developer = 'DEVELOPER',
    ProjectManager = 'PROJECT_MANAGER',
    HrManager = 'HR_MANAGER',
    TeachLeader = 'TEACH_LEADER',
    Tester = 'TESTER',
    TestLeader = 'TEST_LEADER',
    Ceo = 'CEO',
    Sale = 'SALE'
}
export enum UserStatusEnum {
    Active = 'ACTIVE',
    Onboarding = 'ONBOARDING',
    OffBoarding = 'OFF_BOARDING',
    Inactive = 'INACTIVE'
}

