/**
 * OpenApi specification - My Spring App
 * OpenApi document for Spring Security
 *
 * OpenAPI spec version: 1.0
 * Contact: viet.hung.2898@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProfileDto } from '../models/ProfileDto';
import { HttpFile } from '../http/http';

export class UserCreateUpdateRequest {
    'name': string;
    'email': string;
    'password'?: string;
    'position'?: UserCreateUpdateRequestPositionEnum;
    'supervisorId'?: number;
    'roleIds'?: Array<number>;
    'workTimeId'?: number;
    'teamId'?: number;
    'profile'?: ProfileDto;
    'status'?: UserCreateUpdateRequestStatusEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "password",
            "baseName": "password",
            "type": "string",
            "format": ""
        },
        {
            "name": "position",
            "baseName": "position",
            "type": "UserCreateUpdateRequestPositionEnum",
            "format": ""
        },
        {
            "name": "supervisorId",
            "baseName": "supervisorId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "roleIds",
            "baseName": "roleIds",
            "type": "Array<number>",
            "format": "int64"
        },
        {
            "name": "workTimeId",
            "baseName": "workTimeId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "teamId",
            "baseName": "teamId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "profile",
            "baseName": "profile",
            "type": "ProfileDto",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "UserCreateUpdateRequestStatusEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UserCreateUpdateRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum UserCreateUpdateRequestPositionEnum {
    Developer = 'DEVELOPER',
    ProjectManager = 'PROJECT_MANAGER',
    HrManager = 'HR_MANAGER',
    TeachLeader = 'TEACH_LEADER',
    Tester = 'TESTER',
    TestLeader = 'TEST_LEADER',
    Ceo = 'CEO',
    Sale = 'SALE'
}
export enum UserCreateUpdateRequestStatusEnum {
    Active = 'ACTIVE',
    Onboarding = 'ONBOARDING',
    OffBoarding = 'OFF_BOARDING',
    Inactive = 'INACTIVE'
}

