/**
 * OpenApi specification - My Spring App
 * OpenApi document for Spring Security
 *
 * OpenAPI spec version: 1.0
 * Contact: viet.hung.2898@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LocalTime } from '../models/LocalTime';
import { HttpFile } from '../http/http';

export class WorkTime {
    'id'?: number;
    'title'?: string;
    'startTimeMorning': LocalTime;
    'endTimeMorning': LocalTime;
    'startTimeAfternoon': LocalTime;
    'endTimeAfternoon': LocalTime;
    'allowedLateMinutes': number;
    'userId'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "startTimeMorning",
            "baseName": "startTimeMorning",
            "type": "LocalTime",
            "format": ""
        },
        {
            "name": "endTimeMorning",
            "baseName": "endTimeMorning",
            "type": "LocalTime",
            "format": ""
        },
        {
            "name": "startTimeAfternoon",
            "baseName": "startTimeAfternoon",
            "type": "LocalTime",
            "format": ""
        },
        {
            "name": "endTimeAfternoon",
            "baseName": "endTimeAfternoon",
            "type": "LocalTime",
            "format": ""
        },
        {
            "name": "allowedLateMinutes",
            "baseName": "allowedLateMinutes",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return WorkTime.attributeTypeMap;
    }

    public constructor() {
    }
}
