/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AInput: typeof import('ant-design-vue/es')['Input']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuDivider: typeof import('ant-design-vue/es')['MenuDivider']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AMenuItemGroup: typeof import('ant-design-vue/es')['MenuItemGroup']
    APageHeader: typeof import('ant-design-vue/es')['PageHeader']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATag: typeof import('ant-design-vue/es')['Tag']
    DefaultHeader: typeof import('./../components/layout/DefaultHeader.vue')['default']
    DefaultMenu: typeof import('./../components/layout/DefaultMenu.vue')['default']
    DropdownUser: typeof import('./../components/UI/DropdownUser.vue')['default']
    IIonCheckmark: typeof import('~icons/ion/checkmark')['default']
    MenuItemBadge: typeof import('./../components/UI/MenuItemBadge.vue')['default']
    PageLoading: typeof import('./../components/UI/PageLoading.vue')['default']
    ProcessIndicator: typeof import('./../components/UI/ProcessIndicator.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
