/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    AButtonGroup: typeof import('ant-design-vue/es')['ButtonGroup']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuDivider: typeof import('ant-design-vue/es')['MenuDivider']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AMenuItemGroup: typeof import('ant-design-vue/es')['MenuItemGroup']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APageHeader: typeof import('ant-design-vue/es')['PageHeader']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASkeleton: typeof import('ant-design-vue/es')['Skeleton']
    ASkeletonInput: typeof import('ant-design-vue/es')['SkeletonInput']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    DefaultHeader: typeof import('./../components/layout/DefaultHeader.vue')['default']
    DefaultMenu: typeof import('./../components/layout/DefaultMenu.vue')['default']
    DropdownUser: typeof import('./../components/UI/DropdownUser.vue')['default']
    ICarbonAccessibility: typeof import('~icons/carbon/accessibility')['default']
    IIonCheckmark: typeof import('~icons/ion/checkmark')['default']
    IIonChevronBack: typeof import('~icons/ion/chevron-back')['default']
    IIonChevronForward: typeof import('~icons/ion/chevron-forward')['default']
    IIonRefresh: typeof import('~icons/ion/refresh')['default']
    IIonTrashOutline: typeof import('~icons/ion/trash-outline')['default']
    IMdiAccountBox: typeof import('~icons/mdi/account-box')['default']
    MenuItemBadge: typeof import('./../components/UI/MenuItemBadge.vue')['default']
    PageLoading: typeof import('./../components/UI/PageLoading.vue')['default']
    ProcessIndicator: typeof import('./../components/UI/ProcessIndicator.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
